language: r
cache: packages
pandoc_version: 1.19.2.1

addons:
  apt:
    packages:
      - libmagick++-dev
      - libpoppler-cpp-dev
# Set one of your dependencies from CRAN
r_packages:
  - magick
  - pdftools

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
