name: Jekyll site CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check GitHub Pages status
      uses: mcfongtw/CodingInterview@1
      with:
        pages_threshold: major_outage
    - uses: actions/checkout@v3
    - name: Deploy to GitHub Pages
      if: success()
      uses: mcfongtw/CodingInterview@1
      with:
        target_branch: gh-pages
