name: Jekyll site CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check GitHub Pages status
      uses: crazy-max/ghaction-github-status@v3
      with:
        pages_threshold: major_outage
        
    - name: Checkout source code 
      uses: actions/checkout@v3
      
    - name: Deploy to GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v3
      with:
        repo: mcfongtw/CodingInterview
        target_branch: gh-pages
        build_dir: .
